version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgre
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: taskbd
    ports:
      - "5434:5432"
    volumes:
    - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: